import type { Project } from "./types"

export const projectsData: Project[] = [
  {
    id: "astro-ai",
    slug: "astro-ai",
    title: "Astro AI",
    image: "projects/astro-ai",
    imageAlt: "Astro AI - AI-Powered Vedic Astrology Platform on WhatsApp",
    briefDescription:
      "AI-powered Vedic astrology platform delivering personalized astrological insights through WhatsApp. Combines Swiss Ephemeris calculations with GPT-5 for 24/7 accessible, affordable astrology consultations.",
   problem:
  "Professional astrology is often inaccessible — consultations cost $50–$200 per session, require scheduled appointments, and are crowded with non-credible practitioners upselling gems and rituals. This creates high friction and low trust for users seeking genuine, affordable, and immediate guidance.",
    detailedDescription:
      "Astro AI is a conversational astrology platform that combines traditional Vedic astrology principles with modern AI technology. Using Swiss Ephemeris for precise astronomical calculations and GPT-5 for natural language conversations, it delivers personalized astrological insights through WhatsApp. The platform democratizes access to professional-quality astrology by making it affordable ($2.99/month vs $50-200 per consultation), instantly available (24/7 vs appointment-based), and accessible through WhatsApp (no app download required).",
    outcomeBullets: [
      "95% cost reduction vs traditional astrologers ($2.99/month vs $50-200 per consultation)",
      "AI-powered birth chart generation with NASA-grade astronomical accuracy",
      "Multilingual support (English, Hindi, Gujarati) at launch",
      "24/7 availability with instant responses within 5-10 seconds",
    ],
    technologies: [
      "Python",
      "FastAPI",
      "GPT-5",
      "Swiss Ephemeris",
      "PostgreSQL",
      "Redis",
      "WhatsApp Business API",
    ],
    status: "In Progress",
    statusColor: "yellow",
    isFeatured: true,
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "voice-uxr-agent",
    slug: "voice-uxr-automation",
    title: "Voice-Based UXR Agent",
    image: "projects/voice-uxr",
    imageAlt: "Voice-Based User Research Agent",
    briefDescription:
      "AI-powered voice agent system that conducts, transcribes, and analyzes user research interviews at scale. Automated Hunch's user interview process, scaling capacity from 2-3 manual interviews per day to 50+ automated interviews daily.",
    problem:
      "Hunch's user research process was bottlenecked by manual interviews, limiting capacity to 2-3 interviews per day. Each interview required significant time investment and took 3 days to generate insights, making it impossible to scale user research effectively.",
    detailedDescription:
      "Built an AI-powered voice agent system that conducts, transcribes, and analyzes user research interviews at scale. The system automated Hunch's user interview process, scaling capacity from 2-3 manual interviews per day to 50+ automated interviews daily while reducing per-interview cost by 70%. The voice agent conducts natural conversations, asks follow-up questions, performs sentiment analysis, and generates actionable insights—all without human intervention.",
    outcomeBullets: [
      "2,400% capacity increase (2 interviews/day → 50+ interviews/day)",
      "70% cost reduction per interview ($50 → $15)",
      "99% faster insights (3 days → 5 minutes)",
      "82% completion rate with 4.2/5 user satisfaction",
    ],
    technologies: [
      "GPT-o3-mini",
      "ElevenLabs",
      "Twilio",
      "Redshift SQL",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "25x",
    kpiLabel: "Capacity Increase",
    kpiValue: "2 → 50+ interviews/day",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "mbti-matching-system",
    slug: "mbti-personality-matching",
    title: "MBTI Personality Matching System",
    image: "projects/mbti-matching",
    imageAlt: "MBTI-Based Personality Matching System for Hunch Dating App",
    briefDescription:
      "Comprehensive personality matching algorithm integrating MBTI framework with user preferences. Provides transparent 0-100% compatibility scores with detailed explanations, becoming Hunch's core product differentiator.",
    problem:
      "Hunch needed a strong product differentiator to stand out in the competitive dating app market. The app was shifting from anonymous polling to matchmaking but lacked a compelling matching system that could improve user engagement and retention.",
    detailedDescription:
      "Designed and implemented a comprehensive personality matching algorithm that integrates the MBTI (Myers-Briggs Type Indicator) psychological framework with existing user preference filters. This system became Hunch's core product differentiator and fundamentally shifted the app's direction from anonymous polling to personality-based matchmaking. The algorithm provides transparent 0-100% compatibility scores with detailed explanations, helping users understand why they're matched and building trust in the platform.",
    outcomeBullets: [
      "200% increase in average session time (3 min → 9 min)",
      "152% increase in messages per match (2.3 → 5.8)",
      "133% increase in match acceptance rate (15% → 35%)",
      "86% improvement in 7-day retention (22% → 41%)",
      "Became Hunch's core product differentiator",
    ],
    technologies: [
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "200%",
    kpiLabel: "Session Time Increase",
    kpiValue: "3 min → 9 min",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "marketing-analytics-dashboard",
    slug: "marketing-analytics",
    title: "Marketing Analytics Dashboard",
    image: "projects/marketing-analytics-dashboard",
    imageAlt: "Retool Marketing Analytics Dashboard - Unified Analytics & Cost Optimization",
    briefDescription:
      "Consolidated marketing analytics dashboard unifying data from 3 sources (Instagram, Twitter, TikTok) with AI-powered sentiment analysis and trend detection. Replaced 3 expensive SaaS tools while providing better insights.",
    problem:
      "The marketing team was using 3 separate expensive SaaS tools to track performance across Instagram, Twitter, and TikTok. This fragmented approach required 15+ hours of manual work weekly, lacked unified insights, and cost over $1,000 per month in tool subscriptions.",
    detailedDescription:
      "Built a centralized marketing analytics dashboard using Retool that unified data from 3 sources (Instagram, Twitter, TikTok) with AI-powered sentiment analysis and trend detection. Replaced 3 expensive SaaS tools while providing better insights and saving the marketing team 15+ hours of manual work weekly. The dashboard provides real-time metrics, automated comment analysis and viral content pattern identification—all in one interface.",
    outcomeBullets: [
      "$1,000+ cost saved per month",
      "15+ hours/week time savings for marketing team",
      "25% improvement in content engagement rate",
      "Real-time sentiment analysis on 1,000+ daily comments",
    ],
    technologies: [
      "Retool",
      "Redshift SQL",
      "GPT-o3-mini",
      "Apify",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "$1,000+",
    kpiLabel: "Monthly Savings",
    kpiValue: "Replaced 3 SaaS tools",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "fine-tuned-chatbot",
    slug: "fine-tuned-ai-chatbot",
    title: "Fine-Tuned In-App Chatbot",
    image: "projects/fine-tuned-chatbot",
    imageAlt: "Fine-Tuned AI Chatbot for Personalized Conversations",
    briefDescription:
      "Fine-tuned GPT-4o on 450+ carefully curated conversation examples to build a natural, human-like in-app chatbot. It adapts to user tone, discusses diverse topics, and provides personalized responses—improving session time by 100%.",
    problem:
      "Users often struggled to hold meaningful or natural conversations inside the app—leading to low response rates (15%) and shallow conversations averaging only 3.2 messages. This limited user engagement and overall satisfaction.",
      detailedDescription:
      "Led the end-to-end development of Hunch’s Fine-Tuned Chatbot, starting from dataset creation to production deployment. The project began with curating a high-quality dataset of 450+ conversation examples, each scored and cleaned through a structured data-quality framework. This ensured consistent formatting, labeling, and conversational tone across all samples. GPT-4o was then fine-tuned on this dataset to create a model capable of holding natural, personalized, and context-aware conversations. Further collaborated with engineering to integrate the model into the production app serving 100,000+ users, where it became a key engagement driver.",
    outcomeBullets: [
      "180% increase in response rate (15% → 42%)",
      "144% increase in average messages per conversation (3.2 → 7.8)",
      "100% increase in session time (4 min → 8 min)",
      "487% increase in opener usage (8% → 47%)"
    ],
    technologies: [
      "GPT-4o",
      "Redshift SQL"
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "100%",
    kpiLabel: "Session Duration Increase",
    kpiValue: "4 min → 8 min",
    demoUrl: "",
    youtubeUrl: ""
  },
  {
    id: "poll-promotion-engine",
    slug: "poll-promotion-engine",
    title: "Poll Promotion Engine",
    image: "projects/poll-engine",
    imageAlt: "Poll Promotion Engine - Automated Campaign Management & Targeting",
    briefDescription:
      "Automated campaign management interface for targeted poll distribution at Hunch, reducing campaign launch time from 2 days to under 5 minutes while eliminating 85% of manual work. Replaced dependency on Amazon Personalize.",
    problem:
      "Launching poll campaigns required 2 days of manual work involving spreadsheets, SQL queries, and engineering dependencies. The team relied on Amazon Personalize for targeting, which was a black box for us and didn't provide the precision needed for effective campaigns.",
    detailedDescription:
      "Built automated campaign management interface for targeted poll distribution at Hunch, reducing campaign launch time from 2 days to under 5 minutes while eliminating 85% of manual work. System replaced dependency on Amazon Personalize with custom targeting logic and precision audience segmentation. Features include visual campaign builder, precision audience targeting, preview before launch, A/B test setup, real-time performance tracking, and automated scheduling.",
    outcomeBullets: [
      "99% reduction in launch time (2 days → 5 minutes)",
      "85% reduction in manual effort (no spreadsheets, SQL, or engineering dependency)",
      "35% improvement in campaign engagement (better targeting)",
      "3x increase in campaigns launched per month",
    ],
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "Redshift SQL",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "99%",
    kpiLabel: "Time Reduction",
    kpiValue: "2 days → 5 minutes",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "web-onboarding-revenue",
    slug: "web-onboarding-revenue",
    title: "Web Onboarding Revenue Stream",
    image: "projects/web-onboarding",
    imageAlt: "Web Onboarding Revenue Stream - Personality Assessment & App Conversion Funnel",
    briefDescription:
      "Built web-based personality assessment (MBTI test) and app conversion funnel that created entirely new revenue stream for Hunch. Generated $1,500 in revenue from first month, contributing 30% boost to existing revenue.",
    problem:
      "Hunch needed to diversify revenue streams beyond the mobile app. The existing $5,000 monthly revenue was entirely dependent on in-app purchases, and there was no way to capture users who discovered the brand through web search or social media before downloading the app.",
    detailedDescription:
      "Built web-based personality assessment (MBTI test) and app conversion funnel that created entirely new revenue stream for Hunch. Users could take the test on web, see their personality type, purchase a premium plan, and then install the app with their profile pre-loaded. This captured high-intent search traffic and started users with personalized context, increasing conversion efficiency and lifetime value.",
    outcomeBullets: [
      "$1,500+ in revenue added from month one",
      "30% increase in overall monthly revenue",
      "Higher-quality users due to pre-app psychological investment",
      "Seamless profile carryover into app onboarding",
      "New acquisition channel with SEO-optimized landing pages",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Node.js",
      "Redshift SQL",
      "Stripe",
      "Google Workspace",
      "AWS S3",
      "Mixpanel",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "$1,500",
    kpiLabel: "Monthly Revenue",
    kpiValue: "From Month 1",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "newsletter-generator",
    slug: "newsletter-generator",
    title: "Newsletter Generation System",
    image: "projects/newsletter-generator",
    imageAlt: "AI-powered newsletter generation and delivery system",
    briefDescription:
      "AI-driven newsletter generation platform that automates content aggregation, trend detection, and draft creation. Reduces newsletter drafting time from 2-3 hours to under 5 minutes with voice-matched drafts.",
    problem:
      "Creators spend 2-3 hours daily scanning multiple sources (Twitter, YouTube, Reddit, blogs, RSS feeds) to draft newsletters, slowing publishing frequency and hurting consistency. Manual research and drafting prevents creators from focusing on high-value work and maintaining regular publication schedules.",
    detailedDescription:
      "Built CreatorPulse, a production-grade newsletter generation system using Next.js, TypeScript, and Supabase. The system aggregates content from YouTube, Reddit, Twitter, RSS feeds, and blogs, then clusters and ranks emerging topics using custom algorithms. It generates drafts in the creator's writing style using GPT-OSS-20B (via OpenRouter), achieving ≥95% draft readiness. Features include rollback edits, source management toggles, modular pipelines, and cron-based automation for scheduled delivery.",
    outcomeBullets: [
      "Reduced drafting time from 2-3 hours → <5 minutes",
      "≥95% ready drafts with tone and voice alignment",
      "Automated content aggregation from 5+ sources",
      "Clustering-based trend detection and ranking",
      "Cron-scheduled automated delivery at chosen times",
      "Freed creators to focus on high-value work",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "GPT-OSS-20B",
      "Resend",
      "React Query",
      "Tailwind CSS",
      "Vercel Cron Jobs",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    demoUrl: "https://newsletter-self-zeta.vercel.app/",
    youtubeUrl: "https://youtu.be/e7ut-PZs7Hs?si=v3CcnciT0U_7BnWp",
  },
  {
    id: "lecture-lens",
    slug: "lecture-lens-rag-cohort-assistant",
    title: "Lecture Lens - Cohort Assistant",
    image: "projects/lecture-lens",
    imageAlt: "Lecture Lens - AI-Powered Lecture Search & Cohort Assistant",
    briefDescription:
      "AI-powered chat interface that transforms cohort curriculum into a searchable knowledge base. Students ask natural language questions and receive instant answers with precise citations from lectures (with timestamps) and auto-scraped resources.",
    problem:
      "Students struggle to quickly find specific information within extensive lecture materials and scattered resources (GitHub repos, YouTube videos, blog posts). Manual searching through long lecture recordings wastes study time, and there's no way to ask follow-up context-aware questions about course content. This leads to inefficient learning and missed opportunities for deeper understanding.",
    detailedDescription:
      "Lecture Lens is an AI-powered cohort assistant built with Next.js 14 (App Router), React 18, and Tailwind CSS. The system processes VTT lecture transcripts with semantic chunking, auto-scrapes resources from GitHub, YouTube, and blogs, and performs unified vector search across all content using Supabase (PostgreSQL 15 + pgvector). It leverages OpenRouter (Gemini + OpenAI embeddings) and LlamaIndex for AI/ML capabilities. The chat interface provides context-aware conversations with history, multi-cohort authentication with Row Level Security (RLS), hybrid ranking with title matching, and comprehensive timestamped summaries. Built end-to-end RAG pipeline in 24 hours for hackathon submission.",
    outcomeBullets: [
      "Won 1st Runner-Up at hackathon (built in 24 hours)",
      "Complete RAG pipeline with timestamped citations",
      "24/7 instant access to course material with precise citations",
      "Unified vector search across lectures and external resources",
      "Hybrid ranking combining semantic search and title matching",
      "Multi-cohort authentication with Row Level Security (RLS)",
      "Significantly reduced information retrieval time for students",
    ],
    technologies: [
      "Next.js 14",
      "TypeScript",
      "Supabase",
      "LlamaIndex",
      "Gemini 2.5 Flash",
      "OpenAI Embeddings",
      "Vercel Serverless Functions",
      "JWT Authentication",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "1st Runner-Up",
    kpiLabel: "Hackathon",
    kpiValue: "Built in 24 Hours",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "foggy-rainwater-text-generator",
    slug: "foggy-rainwater-text-generator",
    title: "Foggy Rainwater Style Text Generator",
    image: "projects/foggy-rainwater-text",
    imageAlt: "Foggy rainwater style text written on misted glass",
    briefDescription:
      "Custom-trained LoRA model that generates realistic foggy window-style handwritten text and doodles. Created from scratch with no existing dataset, producing natural condensation-on-glass text effects for creative applications.",
    problem:
      "Existing diffusion models like Flux and SDXL could handle graffiti and calligraphy, but no LoRA existed for foggy rainwater glass text—the effect of text written on steamy windows during rainy days. This niche style required building everything from scratch: dataset creation, captioning, and LoRA training with no prior examples to reference.",
    detailedDescription:
      "Built a complete LoRA training pipeline from scratch, starting with concept exploration and dataset creation. Initially attempted TTF/OTF font-based synthetic generation but found text sat artificially 'on top' rather than appearing written 'into' the fog. Switched to manual data collection, scraping ~200 real foggy window images from Pinterest, Google Images, and iStock, then creating ~50 custom Photoshop images to cover symbols, digits, and missing glyphs. Used BLIP-2 for automated captioning of all 250 images. Trained 4 different LoRA versions (150, 80, 60, and 30 images) and discovered that smaller, high-quality datasets (30 & 60 images) outperformed larger ones, proving quality > quantity. The final LoRA handles edge cases including long marketing copy, multiline formulas, emojis, doodles, and math puzzles.",
    outcomeBullets: [
      "250-image curated dataset (200 real + 50 synthetic)",
      "First-of-its-kind LoRA for foggy window text effects",
      "Proved quality > quantity (30-60 images outperformed 150)",
      "Supports emojis, symbols, doodles, multiline text, and formulas",
      "Open-sourced on CivitAI and Hugging Face",
    ],
    technologies: [
      "Flux",
      "LoRA Training",
      "ComfyUI",
      "BLIP-2 Captioning",
      "Photoshop",
      "Jarvis Labs",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    demoUrl: "",
    youtubeUrl: "https://youtu.be/VIGsmIW2Gu0?si=nnnKdpaITykyG0Xt",
  },
]